name: food_distribution_network
description: An intelligent food distribution network application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  intl: ^0.18.1
  http: ^1.1.0
  flutter_local_notifications: ^15.1.0+1
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  

